# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
---
# APPLY_FIXES: all
ENABLE:
  - ACTION
  - HTML
  - JSON
  - MARKDOWN
  - REPOSITORY
  - TYPESCRIPT
  - YAML
DISABLE_LINTERS:
  - TYPESCRIPT_STANDARD
  - JSON_JSONLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - REPOSITORY_DEVSKIM

EXCLUDED_DIRECTORIES: ['megalinter-reports', 'node_modules']
FILTER_REGEX_EXCLUDE: '(pnpm-lock.yaml|pnpm-workspace.yaml)'

JSON_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'
TYPESCRIPT_DEFAULT_STYLE: 'prettier'
TYPESCRIPT_ES_CLI_EXECUTABLE: ['node_modules/.bin/eslint']
TYPESCRIPT_ES_COMMAND_REMOVE_ARGUMENTS:
  - --no-eslintrc
  - -c
  - /tmp/lint/eslint.config.js
  - --no-ignore
TYPESCRIPT_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'
TYPESCRIPT_ES_CONFIG_FILE: 'eslint.config.js'

SHOW_ELAPSED_TIME: true
JSON_REPORTER: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
GITHUB_STATUS_REPORTER: false
PRINT_ALL_FILES: false

LOG_LEVEL: DEBUG
