# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
# // NOTE:  PRE_COMMAND: used for TYPESCRIPT_ES - it uses eslint v8.51.0
---
# APPLY_FIXES: all
ENABLE:
  - TYPESCRIPT
  - HTML
  - JSON
  - MARKDOWN
  - YAML
  - ACTION
  - REPOSITORY
ENABLE_LINTERS:
  - TYPESCRIPT_ES
  - TYPESCRIPT_PRETTIER
DISABLE_LINTERS:
  - TYPESCRIPT_STANDARD
  - JSON_JSONLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - REPOSITORY_DEVSKIM
PRE_COMMANDS:
  - command: export ESLINT_FLAT_CONFIG="true"
    output_variables: ['ESLINT_FLAT_CONFIG']
PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: '(pnpm-lock.yaml|node_modules/|megalinter-reports/)'
JSON_PRETTIER_CONFIG_FILE: './packages/prettier-config/prettier.config.js'
TYPESCRIPT_ES_CONFIG_FILE: './eslint.config.js'
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false
