# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
---
ENABLE:
  - EDITORCONFIG
  - JSON
  - MARKDOWN
  - TYPESCRIPT
  - YAML
DISABLE_LINTERS:
  - TYPESCRIPT_STANDARD

FILTER_REGEX_EXCLUDE: '(pnpm-lock.yaml|pnpm-workspace.yaml)'
EXCLUDED_DIRECTORIES: ['megalinter-reports', 'node_modules']

JSON_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'
TYPESCRIPT_DEFAULT_STYLE: 'prettier'
TYPESCRIPT_ES_CLI_EXECUTABLE: ['node_modules/.bin/eslint']
TYPESCRIPT_ES_COMMAND_REMOVE_ARGUMENTS:
  - --no-eslintrc
  - -c
  - /tmp/lint/eslint.config.js
  - --no-ignore
TYPESCRIPT_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'
TYPESCRIPT_ES_CONFIG_FILE: 'eslint.config.js'

CLEAR_REPORT_FOLDER: true
FLAVOR_SUGGESTIONS: false
MARKDOWN_SUMMARY_REPORTER: true
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
